name: conda-environment

channels:
  - defaults

dependencies:
  - pip
  - python=3.10
  - pip:
    - -r requirements.txt
    # There is a conflict between pybryt and ipykernel>=6.0.0 (released 2 July 2021).
    # Because of that, we fix ipykernel version until version 6.* matures.