site_name: aoc
site_description: Record of current and past attempts at Advent-of-Code in Python
repo_url: https://github.com/sullivancolin/advent_of_code
repo_name: aoc

edit_uri: ""
nav:
  - Home: index.md
  - CLI: CLI.md
  - Day 1:
    - Part 1: day1/part1.md
    - Part 2: day1/part2.md
  - Day 2:
    - Part 1: day2/part1.md
    - Part 2: day2/part2.md
  - Day 4:
    - Part 1: day4/part1.md
    - Part 2: day4/part2.md

theme:
  name: "material"
  font:
    text: "Roboto"
    code: "Fira Code"
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: brandwatch_light
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            annotations_path: source
            show_signature_annotations: true
            separate_signature: true
            members_order: source

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - markdown.extensions.toc:
      permalink: true
      toc_depth: 3

extra_css:
  - "stylesheets/extra.css"
  - "stylesheets/termynal.css"
  - "stylesheets/custom.css"
extra_javascript:
  - "js/termynal.js"
  - "js/custom.js"
